/*
 *
 *  Copyright (C) 2007  Uwe Weng
 *
 *  This file is part of Fuzzy Services, a library for processing fuzzy
 *  information.
 *
 *  Fuzzy Services are free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  Fuzzy Services are distributed in the hope that they will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Fuzzy Services; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 *  The license is also available at http://www.gnu.org/licenses/gpl.txt
 *
 ******************************************************************************/
package net.sourceforge.fuzzyservices.beans;

import net.sourceforge.fuzzyservices.swing.FactBaseModel;

/**
 * Panel for editing fact array property.
 *
 * @version 1.0
 * @author Uwe Weng
 */
public class FactArrayEditorPanel extends javax.swing.JPanel {

    /** Creates new form FactArrayEditorPanel */
    public FactArrayEditorPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        factListEditorPanel = new net.sourceforge.fuzzyservices.swing.FactListEditorPanel();

        setLayout(new java.awt.BorderLayout());

        factListEditorPanel.setName("factListEditorPanel"); // NOI18N
        add(factListEditorPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    net.sourceforge.fuzzyservices.swing.FactListEditorPanel factListEditorPanel;
    // End of variables declaration//GEN-END:variables
    protected FactBaseModel factBaseModel;
    public static final String FACT_BASE_MODEL = "factBaseModel";

    /**
     * Get the value of factBaseModel
     *
     * @return the value of factBaseModel
     */
    public FactBaseModel getFactBaseModel() {
        return factBaseModel;
    }

    /**
     * Set the value of factBaseModel
     *
     * @param factBaseModel new value of factBaseModel
     */
    public void setFactBaseModel(FactBaseModel factBaseModel) {
        FactBaseModel oldFactBaseModel = factBaseModel;
        this.factBaseModel = factBaseModel;
        firePropertyChange(FACT_BASE_MODEL, oldFactBaseModel, factBaseModel);
        factListEditorPanel.setModel(factBaseModel);
    }

    /**
     * Constructs a panel that is initialized with <code>factBaseModel</code> as the model.
     * @param factBaseModel the model for the panel
     */
    public FactArrayEditorPanel(FactBaseModel factBaseModel) {
        this();
        setFactBaseModel(factBaseModel);
    }

}
