/*
 * AntecedentTable.java
 *
 * Created on 2. Februar 2008, 17:22
 */

package net.sourceforge.fuzzyservices.swing;

import javax.swing.JTable;
import javax.swing.table.TableModel;

/**
 *
 * @author  Administrator
 */
public class AntecedentTable extends JTable {
    
    /** Creates new form BeanForm */
    public AntecedentTable() {
        super();
        initComponents();
    }
    
    /** Creates new form BeanForm
     * @param model model for this component
     */
    public AntecedentTable(TableModel model) {
        this();
        setModel(model);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Form"); // NOI18N
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
