/*
 * FactBaseDialog.java
 *
 * Created on 2. Februar 2008, 14:04
 */

package net.sourceforge.fuzzyservices.swing;

import org.jdesktop.application.Action;

/**
 *
 * @author  Administrator
 */
public class FactBaseDialog extends javax.swing.JDialog {
    
    /** Creates new form FactBaseDialog
     * @param parent parent of this component
     * @param modal modal property
     */
    public FactBaseDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** Creates new form FactBaseDialog
     * @param parent parent of this component
     * @param modal modal property
     * @param model model for this component
     */
    public FactBaseDialog(java.awt.Frame parent, boolean modal, FactBaseModel model) {
        this(parent, modal);
        setModel(model);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        factListEditorPanel = new net.sourceforge.fuzzyservices.swing.FactListEditorPanel();
        buttonPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        namePanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        factListEditorPanel.setName("factListEditorPanel"); // NOI18N
        getContentPane().add(factListEditorPanel, java.awt.BorderLayout.CENTER);

        buttonPanel.setName("buttonPanel"); // NOI18N
        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(mydesktopapplication.MyDesktopApplication.class).getContext().getActionMap(FactBaseDialog.class, this);
        okButton.setAction(actionMap.get("ok")); // NOI18N
        okButton.setName("okButton"); // NOI18N
        buttonPanel.add(okButton);

        cancelButton.setAction(actionMap.get("cancel")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N
        buttonPanel.add(cancelButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_END);

        namePanel.setName("namePanel"); // NOI18N
        namePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        nameLabel.setLabelFor(nameTextField);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(mydesktopapplication.MyDesktopApplication.class).getContext().getResourceMap(FactBaseDialog.class);
        nameLabel.setText(resourceMap.getString("nameLabel.text")); // NOI18N
        nameLabel.setName("nameLabel"); // NOI18N
        namePanel.add(nameLabel);

        nameTextField.setColumns(20);
        nameTextField.setAction(actionMap.get("editName")); // NOI18N
        nameTextField.setName("nameTextField"); // NOI18N
        namePanel.add(nameTextField);

        getContentPane().add(namePanel, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FactBaseDialog dialog = new FactBaseDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    @Action
    public void ok() {
    }

    @Action
    public void cancel() {
    }

    @Action
    public void editName() {
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JPanel buttonPanel;
    javax.swing.JButton cancelButton;
    net.sourceforge.fuzzyservices.swing.FactListEditorPanel factListEditorPanel;
    javax.swing.JLabel nameLabel;
    javax.swing.JPanel namePanel;
    javax.swing.JTextField nameTextField;
    javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
    /** Bound property name for <code>model</code>. */
    public static final String MODEL_PROPERTY = "model";
    private FactBaseModel model = new DefaultFactBaseModel();

    /**
     * Defines a new model for this component.
     * @param model The new value for the property.
     * @see #getModel
     */
    public void setModel(FactBaseModel model) {
        FactBaseModel oldModel = this.model;
        this.model = model;
        firePropertyChange(MODEL_PROPERTY, oldModel, model);
    }

    /**
     * Returns the model of this component.
     * @return the <code>model</code> property
     * @see #setModel
     */
    public FactBaseModel getModel() {
        return model;
    }
    
}
