/*
 * LinguisticVariableTabbedPane.java
 *
 * Created on 2. Februar 2008, 17:15
 */

package net.sourceforge.fuzzyservices.swing;

import javax.swing.JTabbedPane;

/**
 *
 * @author  Administrator
 */
public class LinguisticVariableTabbedPane extends JTabbedPane {
    
    /** Creates new form BeanForm */
    public LinguisticVariableTabbedPane() {
        super();
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setName("Form"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(mydesktopapplication.MyDesktopApplication.class).getContext().getResourceMap(LinguisticVariableTabbedPane.class);
        addTab(resourceMap.getString("jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
