/*
 * MembershipFunctionTableEditorPanel.java
 *
 * Created on 2. Februar 2008, 16:07
 */

package net.sourceforge.fuzzyservices.swing;

import org.jdesktop.application.Action;

/**
 *
 * @author  Administrator
 */
public class MembershipFunctionTableEditorPanel extends javax.swing.JPanel {
    
    /** Creates new form MembershipFunctionTableEditorPanel */
    public MembershipFunctionTableEditorPanel() {
        super();
        initComponents();
    }
    
    /** Creates new form MembershipFunctionTableEditorPanel
     * @param model model for this component
     */
    public MembershipFunctionTableEditorPanel(MembershipFunctionModel model) {
        this();
        setModel(model);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        tableScrollPane = new javax.swing.JScrollPane();
        membershipFunctionTable = new net.sourceforge.fuzzyservices.swing.MembershipFunctionTable();

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        buttonPanel.setName("buttonPanel"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(mydesktopapplication.MyDesktopApplication.class).getContext().getActionMap(MembershipFunctionTableEditorPanel.class, this);
        addButton.setAction(actionMap.get("addPoint")); // NOI18N
        addButton.setName("addButton"); // NOI18N

        removeButton.setAction(actionMap.get("removePoint")); // NOI18N
        removeButton.setName("removeButton"); // NOI18N

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(removeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(248, Short.MAX_VALUE))
        );

        add(buttonPanel, java.awt.BorderLayout.LINE_END);

        tableScrollPane.setName("tableScrollPane"); // NOI18N

        membershipFunctionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        membershipFunctionTable.setName("membershipFunctionTable"); // NOI18N
        tableScrollPane.setViewportView(membershipFunctionTable);

        add(tableScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void addPoint() {
    }

    @Action
    public void removePoint() {
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton addButton;
    javax.swing.JPanel buttonPanel;
    net.sourceforge.fuzzyservices.swing.MembershipFunctionTable membershipFunctionTable;
    javax.swing.JButton removeButton;
    javax.swing.JScrollPane tableScrollPane;
    // End of variables declaration//GEN-END:variables
    /** Bound property name for <code>model</code>. */
    public static final String MODEL_PROPERTY = "model";
    private MembershipFunctionModel model = new DefaultMembershipFunctionModel();

    /**
     * Defines a new model for this component.
     * @param model The new value for the property.
     * @see #getModel
     */
    public void setModel(MembershipFunctionModel model) {
        MembershipFunctionModel oldModel = this.model;
        this.model = model;
        firePropertyChange(MODEL_PROPERTY, oldModel, model);
    }

    /**
     * Returns the model of this component.
     * @return the <code>model</code> property
     * @see #setModel
     */
    public MembershipFunctionModel getModel() {
        return model;
    }
    
}
