/*
 * RuleList.java
 *
 * Created on 2. Februar 2008, 17:25
 */

package net.sourceforge.fuzzyservices.swing;

import javax.swing.JList;

/**
 *
 * @author  Administrator
 */
public class RuleList extends JList {
    
    /** Creates new form BeanForm */
    public RuleList() {
        super();
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Form"); // NOI18N
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
