/*
 * FactBeanArrayEditorPanel.java
 *
 * Created on 11. November 2007, 12:17
 */
package net.sourceforge.fuzzyservices.beans;

/**
 *
 * @author  Administrator
 */
public class FactBeanArrayEditorPanel extends javax.swing.JPanel {

    /**
     * Creates new form RuleBeanArrayEditorPanel
     */
    public FactBeanArrayEditorPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eastPanel = new javax.swing.JPanel();
        buttonPanel1 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        buttonPanel2 = new javax.swing.JPanel();
        editButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        listScrollPane = new javax.swing.JScrollPane();
        factList = new javax.swing.JList();

        setLayout(new java.awt.BorderLayout(10, 0));

        eastPanel.setLayout(new java.awt.BorderLayout());

        buttonPanel1.setLayout(new java.awt.BorderLayout(0, 5));

        addButton.setMnemonic(java.util.ResourceBundle.getBundle("net/sourceforge/fuzzyservices/beans/resources").getString("FACT_BEAN_ARRAY_EDITOR_PANEL_ADD_BUTTON_TEXT").charAt(0));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("net/sourceforge/fuzzyservices/beans/resources"); // NOI18N
        addButton.setText(bundle.getString("FACT_BEAN_ARRAY_EDITOR_PANEL_ADD_BUTTON_TEXT")); // NOI18N
        addButton.setToolTipText(bundle.getString("FACT_BEAN_ARRAY_EDITOR_PANEL_ADD_BUTTON_TOOLTIPTEXT")); // NOI18N
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent event) {
                addButtonActionPerformed(event);
            }
        });
        buttonPanel1.add(addButton, java.awt.BorderLayout.NORTH);

        buttonPanel2.setLayout(new java.awt.BorderLayout(0, 5));

        editButton.setText("edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent event) {
                editButtonActionPerformed(event);
            }
        });
        buttonPanel2.add(editButton, java.awt.BorderLayout.SOUTH);

        removeButton.setText("remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent event) {
                removeButtonActionPerformed(event);
            }
        });
        buttonPanel2.add(removeButton, java.awt.BorderLayout.NORTH);

        buttonPanel1.add(buttonPanel2, java.awt.BorderLayout.SOUTH);

        eastPanel.add(buttonPanel1, java.awt.BorderLayout.NORTH);

        add(eastPanel, java.awt.BorderLayout.EAST);

        factList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listScrollPane.setViewportView(factList);

        add(listScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_editButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_removeButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel buttonPanel1;
    private javax.swing.JPanel buttonPanel2;
    private javax.swing.JPanel eastPanel;
    private javax.swing.JButton editButton;
    private javax.swing.JList factList;
    private javax.swing.JScrollPane listScrollPane;
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables
}
