/*
 * FuzzySetBeanEditorPanel.java
 *
 * Created on 4. November 2007, 12:28
 */

package net.sourceforge.fuzzyservices.beans;

/**
 *
 * @author  Administrator
 */
public class FuzzySetBeanEditorPanel extends javax.swing.JPanel {
    
    /** Creates new form FuzzySetBeanEditorPanel */
    public FuzzySetBeanEditorPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
