/*
 * MembershipFunctionPointBeanArrayEditorPanel.java
 *
 * Created on 4. November 2007, 08:58
 */

package net.sourceforge.fuzzyservices.beans;

import net.sourceforge.fuzzyservices.swing.MembershipFunctionModel;

/**
 *
 * @author  Administrator
 */
public class MembershipFunctionPointBeanArrayEditorPanel extends javax.swing.JPanel {
    
    /** Creates new form MembershipFunctionPointBeanArrayEditorPanel */
    public MembershipFunctionPointBeanArrayEditorPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        membershipFunctionPanel1 = new net.sourceforge.fuzzyservices.swing.MembershipFunctionPanel();

        setLayout(new java.awt.BorderLayout());

        add(membershipFunctionPanel1, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private net.sourceforge.fuzzyservices.swing.MembershipFunctionPanel membershipFunctionPanel1;
    // End of variables declaration//GEN-END:variables

    /**
     * Holds value of property membershipFunctionModel.
     */
    private MembershipFunctionModel membershipFunctionModel;

    /**
     * Getter for property membershipFunctionModel.
     * @return Value of property membershipFunctionModel.
     */
    public MembershipFunctionModel getMembershipFunctionModel() {
        return this.membershipFunctionModel;
    }

    /**
     * Setter for property membershipFunctionModel.
     * @param membershipFunctionModel New value of property membershipFunctionModel.
     */
    public void setMembershipFunctionModel(MembershipFunctionModel membershipFunctionModel) {
        MembershipFunctionModel oldMembershipFunctionModel = this.membershipFunctionModel;
        this.membershipFunctionModel = membershipFunctionModel;
        firePropertyChange ("membershipFunctionModel", oldMembershipFunctionModel, membershipFunctionModel);
        membershipFunctionPanel1.setModel(this.membershipFunctionModel);
    }
   
}
