/*
 * OperatorBeanEditorPanel.java
 *
 * Created on 7. Oktober 2007, 13:12
 */

package net.sourceforge.fuzzyservices.beans;

/**
 *
 * @author  Administrator
 */
public class OperatorBeanEditorPanel extends javax.swing.JPanel {
    
    private OperatorBean model;
    
    /**
     * Creates new form OperatorBeanEditorPanel
     */
    public OperatorBeanEditorPanel() {
        initComponents();
    }
    
    /**
     * Creates new form OperatorBeanEditorPanel
     */
    public OperatorBeanEditorPanel(OperatorBean model) {
        this.model = model;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        typeComboBox = new javax.swing.JComboBox();
        withLabel = new javax.swing.JLabel();
        parameterTextField = new javax.swing.JTextField();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        typeComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typeComboBoxItemStateChanged(evt);
            }
        });

        add(typeComboBox);

        withLabel.setLabelFor(parameterTextField);
        withLabel.setText("with");
        add(withLabel);

        parameterTextField.setText("jTextField1");
        add(parameterTextField);

    }// </editor-fold>//GEN-END:initComponents

    private void typeComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typeComboBoxItemStateChanged

    }//GEN-LAST:event_typeComboBoxItemStateChanged
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField parameterTextField;
    private javax.swing.JComboBox typeComboBox;
    private javax.swing.JLabel withLabel;
    // End of variables declaration//GEN-END:variables
    
}
