/*
 * SimpleAttributePanel.java
 *
 * Created on 14. Oktober 2007, 11:46
 */
package net.sourceforge.fuzzyservices.beans;


/**
 *
 * @author  Administrator
 */
public class SimpleAttributePanel extends javax.swing.JPanel {
    // Variables declaration - do not modify                     
    private javax.swing.JTextField jTextField1;
    private net.sourceforge.fuzzyservices.beans.SimpleAttribute simpleAttribute1;
    private net.sourceforge.fuzzyservices.beans.SimpleBean simpleBean1;

    /** Creates new form SimpleAttributePanel */
    public SimpleAttributePanel(SimpleAttribute sa) {
        simpleAttribute1 = sa;
        initComponents();
    }

    public SimpleAttributePanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        simpleAttribute1 = getSimpleAttribute1();
        simpleBean1 = new net.sourceforge.fuzzyservices.beans.SimpleBean();
        jTextField1 = new javax.swing.JTextField();

        simpleAttribute1.setText("Test");

        setLayout(new java.awt.BorderLayout());

        jTextField1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
                public final void propertyChange(java.beans.PropertyChangeEvent evt) {
                    jTextField1PropertyChange(evt);
                }
            });
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
                public final void focusLost(java.awt.event.FocusEvent evt) {
                    jTextField1FocusLost(evt);
                }
            });

        add(jTextField1, java.awt.BorderLayout.NORTH);
    } // </editor-fold>//GEN-END:initComponents

    private void jTextField1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextField1PropertyChange
        System.out.println("jTextField1PropertyChange called");
        System.out.println(evt.getPropertyName());
        System.out.println(evt.getOldValue());
        System.out.println(evt.getNewValue());
    }//GEN-LAST:event_jTextField1PropertyChange

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        System.out.println("jTextField1FocusLost called");

        if (simpleAttribute1 != null) {
            String oldText = simpleAttribute1.getText();
            String newText = jTextField1.getText();
            simpleAttribute1.setText(newText);
            firePropertyChange("SIMPLETEXT", oldText, newText);
        } else {
            System.out.println("simpelAttribute1 is null.");
        }
    }//GEN-LAST:event_jTextField1FocusLost

    private SimpleAttribute getSimpleAttribute1() {
        return simpleAttribute1;
    }

    // End of variables declaration                   
}
