/*
 *
 *  Copyright (C) 2007  Uwe Weng
 *
 *  This file is part of Fuzzy Services, a library for processing fuzzy
 *  information.
 *
 *  Fuzzy Services are free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  Fuzzy Services are distributed in the hope that they will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Fuzzy Services; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 *  The license is also available at http://www.gnu.org/licenses/gpl.txt
 *
 ******************************************************************************/
package net.sourceforge.fuzzyservices.beans;

import net.sourceforge.fuzzyservices.swing.MembershipFunctionModel;

/**
 * Panel for editing membership function property.
 *
 * @version 1.0
 * @author Uwe Weng
 */
public class MembershipFunctionEditorPanel extends javax.swing.JPanel {

    /** Creates new form MembershipFunctionEditorPanel */
    public MembershipFunctionEditorPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        membershipFunctionPanel = new net.sourceforge.fuzzyservices.swing.MembershipFunctionPanel();
        membershipFunctionTableEditorPanel = new net.sourceforge.fuzzyservices.swing.MembershipFunctionTableEditorPanel();

        setLayout(new java.awt.BorderLayout());

        membershipFunctionPanel.setName("membershipFunctionPanel"); // NOI18N

        javax.swing.GroupLayout membershipFunctionPanelLayout = new javax.swing.GroupLayout(membershipFunctionPanel);
        membershipFunctionPanel.setLayout(membershipFunctionPanelLayout);
        membershipFunctionPanelLayout.setHorizontalGroup(
            membershipFunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 701, Short.MAX_VALUE)
        );
        membershipFunctionPanelLayout.setVerticalGroup(
            membershipFunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
        );

        add(membershipFunctionPanel, java.awt.BorderLayout.CENTER);

        membershipFunctionTableEditorPanel.setName("membershipFunctionTableEditorPanel"); // NOI18N
        add(membershipFunctionTableEditorPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    net.sourceforge.fuzzyservices.swing.MembershipFunctionPanel membershipFunctionPanel;
    net.sourceforge.fuzzyservices.swing.MembershipFunctionTableEditorPanel membershipFunctionTableEditorPanel;
    // End of variables declaration//GEN-END:variables
    protected MembershipFunctionModel membershipFunctionModel;
    public static final String MEMBERSHIP_FUNCTION_MODEL_PROPERTY = "membershipFunctionModel";

    /**
     * Get the value of membershipFunctionModel
     *
     * @return the value of membershipFunctionModel
     */
    public MembershipFunctionModel getMembershipFunctionModel() {
        return membershipFunctionModel;
    }

    /**
     * Set the value of membershipFunctionModel
     *
     * @param membershipFunctionModel new value of membershipFunctionModel
     */
    public void setMembershipFunctionModel(MembershipFunctionModel membershipFunctionModel) {
        MembershipFunctionModel oldMembershipFunctionModel = membershipFunctionModel;
        this.membershipFunctionModel = membershipFunctionModel;
        firePropertyChange(MEMBERSHIP_FUNCTION_MODEL_PROPERTY, oldMembershipFunctionModel, membershipFunctionModel);
        membershipFunctionPanel.setModel(membershipFunctionModel);
        membershipFunctionTableEditorPanel.setModel(membershipFunctionModel);
    }

    /**
     * Constructs a panel that is initialized with <code>membershipFunctionModel</code> as the model.
     * @param membershipFunctionModel the model for the panel
     */
    public MembershipFunctionEditorPanel(MembershipFunctionModel membershipFunctionModel) {
        this();
        setMembershipFunctionModel(membershipFunctionModel);
    }
}
